package pantallas;

import bibliotecas.BusquedaOrdenacion;
import java.util.ArrayList;
import static javaflix.JavaFlixMain.archivo;
import static javaflix.JavaFlixMain.contenidos;
import static javaflix.JavaFlixMain.usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetos.*;

/**
 * Pantalla de administracion de contenidos
 * 
 * @author Raul
 */
public class AdministracionContenidos extends javax.swing.JFrame {
    
    // Variable para tener a mano el contenido seleccionado

    static Contenido contenidoSeleccionado;
    
    //Contenido a mostrar ordenado
    
    ArrayList<Contenido> contenidoMostrar;
    
    /**
     * Constructor
     */
    public AdministracionContenidos() {
        
        initComponents();
        this.getContentPane().setBackground(getBackground());
        this.setLocationRelativeTo(null);
        this.setTitle("JavaFlix. Aministrador");
        ImageIcon icono = new ImageIcon("img/imgdisenno/logo.jpg");
        setIconImage(icono.getImage());
        actualizarContenidos();
        contenidoMostrar = BusquedaOrdenacion.ordenarContenidos(BusquedaOrdenacion.TipoOrdenacionContenido.TITULO, contenidoMostrar);
        cargarContenidos(contenidoMostrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botVolver = new javax.swing.JButton();
        botCrearContenido = new javax.swing.JButton();
        botModificarContenido = new javax.swing.JButton();
        botBorrarContenido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaContenidos = new javax.swing.JList<>();
        buscador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tipoBusqueda = new javax.swing.JComboBox<>();
        actores = new javax.swing.JRadioButton();
        genero = new javax.swing.JComboBox<>();
        anno = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ordAnno = new javax.swing.JRadioButton();
        ordTitulo = new javax.swing.JRadioButton();
        ordValoracion = new javax.swing.JRadioButton();
        palabrasClave = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1200, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botVolver.setBackground(new java.awt.Color(255, 0, 0));
        botVolver.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        botVolver.setForeground(new java.awt.Color(255, 255, 255));
        botVolver.setText("Volver");
        botVolver.setBorderPainted(false);
        botVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botVolverMouseExited(evt);
            }
        });
        botVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, 250, 100));

        botCrearContenido.setBackground(new java.awt.Color(255, 0, 0));
        botCrearContenido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        botCrearContenido.setForeground(new java.awt.Color(255, 255, 255));
        botCrearContenido.setText("Crear Contenido");
        botCrearContenido.setBorderPainted(false);
        botCrearContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botCrearContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botCrearContenidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botCrearContenidoMouseExited(evt);
            }
        });
        botCrearContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearContenidoActionPerformed(evt);
            }
        });
        getContentPane().add(botCrearContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 250, 100));

        botModificarContenido.setBackground(new java.awt.Color(255, 0, 0));
        botModificarContenido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        botModificarContenido.setForeground(new java.awt.Color(255, 255, 255));
        botModificarContenido.setText("Ver/Modificar Contenido");
        botModificarContenido.setBorderPainted(false);
        botModificarContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botModificarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botModificarContenidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botModificarContenidoMouseExited(evt);
            }
        });
        botModificarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botModificarContenidoActionPerformed(evt);
            }
        });
        getContentPane().add(botModificarContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 250, 100));

        botBorrarContenido.setBackground(new java.awt.Color(255, 0, 0));
        botBorrarContenido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        botBorrarContenido.setForeground(new java.awt.Color(255, 255, 255));
        botBorrarContenido.setText("Borrar Contenido");
        botBorrarContenido.setBorderPainted(false);
        botBorrarContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botBorrarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botBorrarContenidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botBorrarContenidoMouseExited(evt);
            }
        });
        botBorrarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBorrarContenidoActionPerformed(evt);
            }
        });
        getContentPane().add(botBorrarContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 250, 100));

        listaContenidos.setBackground(new java.awt.Color(255, 255, 255));
        listaContenidos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        listaContenidos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listaContenidos.setForeground(new java.awt.Color(0, 0, 0));
        listaContenidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaContenidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 1070, 470));

        buscador.setBackground(new java.awt.Color(255, 255, 255));
        buscador.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buscador.setForeground(new java.awt.Color(87, 87, 87));
        buscador.setText("Introduce la búsqueda");
        buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscadorFocusLost(evt);
            }
        });
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscadorKeyTyped(evt);
            }
        });
        getContentPane().add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 360, 50));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        tipoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        tipoBusqueda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        tipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Serie", "Pelicula" }));
        tipoBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(tipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 170, 50));

        actores.setBackground(new java.awt.Color(0, 0, 0));
        actores.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        actores.setForeground(new java.awt.Color(255, 255, 255));
        actores.setText("Actores");
        actores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actoresActionPerformed(evt);
            }
        });
        getContentPane().add(actores, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        genero.setBackground(new java.awt.Color(255, 255, 255));
        genero.setForeground(new java.awt.Color(0, 0, 0));
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Acción", "Aventura", "Catástrofe", "Ciencia Ficción", "Comedia", "Drama", "Fantasía", "Musicales", "Suspense", "Terror" }));
        genero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 120, 30));

        anno.setBackground(new java.awt.Color(255, 255, 255));
        anno.setForeground(new java.awt.Color(0, 0, 0));
        anno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));
        anno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annoActionPerformed(evt);
            }
        });
        getContentPane().add(anno, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Contenido:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ordenar por:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JAVAFLIX");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 30));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Género:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        ordAnno.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(ordAnno);
        ordAnno.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ordAnno.setForeground(new java.awt.Color(255, 255, 255));
        ordAnno.setText("Año");
        ordAnno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordAnnoActionPerformed(evt);
            }
        });
        getContentPane().add(ordAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, -1, 30));

        ordTitulo.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(ordTitulo);
        ordTitulo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ordTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ordTitulo.setSelected(true);
        ordTitulo.setText("Título");
        ordTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordTituloActionPerformed(evt);
            }
        });
        getContentPane().add(ordTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, -1, 30));

        ordValoracion.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(ordValoracion);
        ordValoracion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ordValoracion.setForeground(new java.awt.Color(255, 255, 255));
        ordValoracion.setText("Valoración");
        ordValoracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordValoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordValoracionActionPerformed(evt);
            }
        });
        getContentPane().add(ordValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, -1, 30));

        palabrasClave.setBackground(new java.awt.Color(0, 0, 0));
        palabrasClave.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        palabrasClave.setForeground(new java.awt.Color(255, 255, 255));
        palabrasClave.setText("Palabras clave");
        palabrasClave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        palabrasClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabrasClaveActionPerformed(evt);
            }
        });
        getContentPane().add(palabrasClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVolverActionPerformed

        // Abre pantalla de administrador
        JavaFlixAdministrador jFA = new JavaFlixAdministrador();
        jFA.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botVolverActionPerformed

    private void botCrearContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearContenidoActionPerformed
        
        // Pregunta si serie o película
        String[] tipoContenido = {"Serie", "Película"};
        int opcion = JOptionPane.showOptionDialog(this, "Elija el tipo de contenido que desea crear", "Tipo de contenido",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, tipoContenido, tipoContenido[0]);
        switch (opcion) {
            case 0: {
                contenidoSeleccionado = null;
                this.dispose();
                CrearModificarSerie crearSerie = new CrearModificarSerie();
                crearSerie.setVisible(true);
                break;
            } case 1: {
                contenidoSeleccionado = null;
                this.dispose();
                CrearModificarPelicula crearPelicula = new CrearModificarPelicula();
                crearPelicula.setVisible(true);
                break;
            }
        }
        
    }//GEN-LAST:event_botCrearContenidoActionPerformed

    private void botModificarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botModificarContenidoActionPerformed
        try {
            // Indice del contenido en el JList
            int indice = listaContenidos.getSelectedIndex();
            Contenido contenidoSeleccionadoMuestra = contenidoMostrar.get(indice);
            contenidoSeleccionado = contenidos.get(contenidos.indexOf(contenidoSeleccionadoMuestra));
            // Abre pantalla modificar contenido
            contenidoSeleccionado.crearModificarContenido();
            this.dispose();
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "Ningún Contenido Seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);};
    }//GEN-LAST:event_botModificarContenidoActionPerformed

    private void botBorrarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBorrarContenidoActionPerformed
        
        // Indice del contenido en el JList
        int indice = listaContenidos.getSelectedIndex();
        if (indice != -1) {
            // Pregunta para asegurar
            String[] opciones = {"Sí", "No"};
            int eleccion = JOptionPane.showOptionDialog(this, "¿Está seguro de que quiere borrar el contenido? La acción es irreversible",
                    "Confirme la acción", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[1]);
            if (eleccion == 0) {

                Contenido contenidoSeleccionadoMuestra = contenidoMostrar.get(indice);
                contenidoSeleccionado = contenidos.get(contenidos.indexOf(contenidoSeleccionadoMuestra));
                // Borra contenido
                ((Administrador) usuario).borrarContenido(contenidoSeleccionado, contenidos);
                archivo.guardarArchivo("contenidos.dat", contenidos);
                actualizarContenidos();
                cargarContenidos(contenidoMostrar);
            } 
        } else JOptionPane.showMessageDialog(this, "Ningún Contenido Seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botBorrarContenidoActionPerformed

    
    // El siguiente bloque de métodos actualizan automáticamente los contenidos de la búsqueda
    
    private void tipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBusquedaActionPerformed
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_tipoBusquedaActionPerformed

    private void actoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actoresActionPerformed
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_actoresActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_generoActionPerformed

    private void annoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annoActionPerformed
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_annoActionPerformed

    private void buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyTyped
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_buscadorKeyTyped

    private void ordAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordAnnoActionPerformed
        contenidoMostrar = BusquedaOrdenacion.ordenarContenidos(BusquedaOrdenacion.TipoOrdenacionContenido.ANNO, contenidoMostrar);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_ordAnnoActionPerformed

    private void ordTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordTituloActionPerformed
        contenidoMostrar = BusquedaOrdenacion.ordenarContenidos(BusquedaOrdenacion.TipoOrdenacionContenido.TITULO, contenidoMostrar);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_ordTituloActionPerformed

    private void ordValoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordValoracionActionPerformed
        contenidoMostrar = BusquedaOrdenacion.ordenarContenidos(BusquedaOrdenacion.TipoOrdenacionContenido.VALORACION, contenidoMostrar);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_ordValoracionActionPerformed
    
    private void botCrearContenidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCrearContenidoMouseEntered
        // Botón rojo oscuro
        botCrearContenido.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_botCrearContenidoMouseEntered

    private void botCrearContenidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCrearContenidoMouseExited
        // Botón rojo
        botCrearContenido.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_botCrearContenidoMouseExited

    private void botModificarContenidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botModificarContenidoMouseEntered
        // Botón rojo oscuro
        botModificarContenido.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_botModificarContenidoMouseEntered

    private void botModificarContenidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botModificarContenidoMouseExited
        // Botón rojo
        botModificarContenido.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_botModificarContenidoMouseExited

    private void botBorrarContenidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botBorrarContenidoMouseEntered
        // Botón rojo oscuro
        botBorrarContenido.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_botBorrarContenidoMouseEntered

    private void botBorrarContenidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botBorrarContenidoMouseExited
        // Botón rojo
        botBorrarContenido.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_botBorrarContenidoMouseExited

    private void botVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botVolverMouseEntered
        // Botón rojo oscuro
        botVolver.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_botVolverMouseEntered

    private void botVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botVolverMouseExited
        // Botón rojo
        botVolver.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_botVolverMouseExited

    private void palabrasClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabrasClaveActionPerformed
        contenidoMostrar = BusquedaOrdenacion.buscarContenido((String) tipoBusqueda.getSelectedItem(), actores.isSelected(),
                buscador.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(), palabrasClave.isSelected(), contenidos);
        cargarContenidos(contenidoMostrar);
    }//GEN-LAST:event_palabrasClaveActionPerformed

    private void buscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscadorFocusLost
        if (buscador.getText().equals("")) {
            buscador.setText("Introduce la búsqueda");
            buscador.setForeground(new java.awt.Color(87,87,87));}
    }//GEN-LAST:event_buscadorFocusLost

    private void buscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscadorFocusGained
        if (buscador.getText().equals("Introduce la búsqueda")) {
            buscador.setText("");
            buscador.setForeground(new java.awt.Color(0,0,0));}
    }//GEN-LAST:event_buscadorFocusGained

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionContenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionContenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionContenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionContenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionContenidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actores;
    private javax.swing.JComboBox<String> anno;
    private javax.swing.JButton botBorrarContenido;
    private javax.swing.JButton botCrearContenido;
    private javax.swing.JButton botModificarContenido;
    private javax.swing.JButton botVolver;
    private javax.swing.JTextField buscador;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaContenidos;
    private javax.swing.JRadioButton ordAnno;
    private javax.swing.JRadioButton ordTitulo;
    private javax.swing.JRadioButton ordValoracion;
    private javax.swing.JRadioButton palabrasClave;
    private javax.swing.JComboBox<String> tipoBusqueda;
    // End of variables declaration//GEN-END:variables

    // Mis métodos
    

    // Lee contenidos del archivo

    private void actualizarContenidos() {
        
        contenidos = (ArrayList<Contenido>) archivo.leerArchivo("contenidos.dat");
        contenidoMostrar = contenidos;
    }
    
    // Carga contenidos en el JList
    private void cargarContenidos(ArrayList<Contenido> contenidos) {
        
        String[] contenidosLista = new String[contenidos.size()];
        for (int i = 0 ; i < contenidosLista.length ; i++) {
            contenidosLista[i] = contenidos.get(i).toString();
        }
        listaContenidos.setListData(contenidosLista);
        
    }
    

}
