package pantallas;

import java.awt.Image;
import java.util.ArrayList;
import static javaflix.JavaFlixMain.archivo;
import static javaflix.JavaFlixMain.contenidos;
import static javaflix.JavaFlixMain.usuario;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import objetos.Administrador;
import objetos.Capitulo;
import objetos.Serie;
import static pantallas.AdministracionContenidos.contenidoSeleccionado;

/**
 * Pantalla para crear y modificar serie
 * 
 * @author Raul
 */
public class CrearModificarSerie extends javax.swing.JFrame {
    
    private boolean crear;
    private ArrayList<ArrayList<Capitulo>> capitulosTemporada;
    
    /**
     * Constructor
     */
    public CrearModificarSerie() {
        initComponents();
        this.getContentPane().setBackground(getBackground());
        this.setLocationRelativeTo(null);
        this.setTitle("JavaFlix. Añadir Serie.");
        ImageIcon icono = new ImageIcon("img/imgdisenno/logo.jpg");
        setIconImage(icono.getImage());
        panelMostrarContenido.setVisible(false);
        crear = false;
        capitulosTemporada = new ArrayList<ArrayList<Capitulo>>();

        try {
            titulo.setText(contenidoSeleccionado.getTitulo());
            titulo.setEditable(false);
            sinopsis.setText(contenidoSeleccionado.getSinopsis());
            genero.setSelectedItem(contenidoSeleccionado.getGenero());
            anno.setSelectedItem(contenidoSeleccionado.getAnno());
            actores.setText(contenidoSeleccionado.actoresToString());
            imagenPortada.setText(contenidoSeleccionado.getImagenPortada());
            capitulosTemporada = ((Serie) contenidoSeleccionado).getTemporadas();
            actualizarTemporadas();
            listaTemporadas.setSelectedIndex(0);
            actualizarCapitulos(0);
            crearModificarContenido.setText("Modificar Serie");
            tituloPantalla.setText("MODIFICAR SERIE");
            
        } catch (java.lang.NullPointerException e) {
            crear = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        panelMostrarContenido = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sinopsisMostrar = new javax.swing.JTextArea();
        tituloMostrar = new javax.swing.JLabel();
        genAnnoVal = new javax.swing.JLabel();
        actoresMostrar = new javax.swing.JLabel();
        calificacion = new javax.swing.JComboBox<>();
        favoritos = new javax.swing.JButton();
        temporadas = new javax.swing.JComboBox<>();
        verCaps = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelCrearModificarSerie = new javax.swing.JPanel();
        crearModificarContenido = new javax.swing.JButton();
        borrarCapitulo = new javax.swing.JButton();
        addCapitulo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCapitulos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTemporadas = new javax.swing.JList<>();
        borrarTemporada = new javax.swing.JButton();
        addTemporada = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        imagenPortada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addImagen = new javax.swing.JButton();
        actores = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopsis = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        tituloPantalla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        previsualizar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelMostrarContenido.setBackground(new java.awt.Color(31, 31, 31));
        panelMostrarContenido.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(74, 1, 1)));
        panelMostrarContenido.setForeground(new java.awt.Color(255, 255, 255));
        panelMostrarContenido.setMaximumSize(new java.awt.Dimension(671, 658));
        panelMostrarContenido.setMinimumSize(new java.awt.Dimension(671, 658));
        panelMostrarContenido.setPreferredSize(new java.awt.Dimension(671, 658));
        panelMostrarContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setBackground(new java.awt.Color(0, 0, 0));
        imagen.setForeground(new java.awt.Color(255, 255, 255));
        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMostrarContenido.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 290, 180));

        sinopsisMostrar.setEditable(false);
        sinopsisMostrar.setBackground(new java.awt.Color(0, 0, 0));
        sinopsisMostrar.setColumns(50);
        sinopsisMostrar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sinopsisMostrar.setForeground(new java.awt.Color(255, 255, 255));
        sinopsisMostrar.setLineWrap(true);
        sinopsisMostrar.setRows(9);
        sinopsisMostrar.setWrapStyleWord(true);
        sinopsisMostrar.setAlignmentX(10.0F);
        sinopsisMostrar.setAlignmentY(10.0F);
        sinopsisMostrar.setBorder(null);
        sinopsisMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sinopsisMostrar.setFocusable(false);
        jScrollPane4.setViewportView(sinopsisMostrar);

        panelMostrarContenido.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 570, 170));

        tituloMostrar.setBackground(new java.awt.Color(0, 0, 0));
        tituloMostrar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        tituloMostrar.setForeground(new java.awt.Color(255, 255, 255));
        tituloMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMostrarContenido.add(tituloMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 260, 50));

        genAnnoVal.setBackground(new java.awt.Color(0, 0, 0));
        genAnnoVal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        genAnnoVal.setForeground(new java.awt.Color(255, 255, 255));
        genAnnoVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMostrarContenido.add(genAnnoVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 280, 30));

        actoresMostrar.setBackground(new java.awt.Color(0, 0, 0));
        actoresMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        actoresMostrar.setForeground(new java.awt.Color(255, 255, 255));
        actoresMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMostrarContenido.add(actoresMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 570, 60));

        calificacion.setBackground(new java.awt.Color(255, 255, 255));
        calificacion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        calificacion.setForeground(new java.awt.Color(0, 0, 0));
        calificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No calificado", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        calificacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calificacion.setLightWeightPopupEnabled(false);
        panelMostrarContenido.add(calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 150, 40));

        favoritos.setBackground(new java.awt.Color(255, 0, 0));
        favoritos.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        favoritos.setForeground(new java.awt.Color(255, 255, 255));
        favoritos.setText("AÑADIR A FAVORITOS");
        favoritos.setBorderPainted(false);
        favoritos.setContentAreaFilled(false);
        favoritos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMostrarContenido.add(favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 190, 40));

        temporadas.setBackground(new java.awt.Color(255, 255, 255));
        temporadas.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        temporadas.setForeground(new java.awt.Color(0, 0, 0));
        temporadas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        temporadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temporadas.setLightWeightPopupEnabled(false);
        panelMostrarContenido.add(temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 120, 30));

        verCaps.setBackground(new java.awt.Color(255, 0, 0));
        verCaps.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        verCaps.setForeground(new java.awt.Color(255, 255, 255));
        verCaps.setText("CAPITULOS");
        verCaps.setBorderPainted(false);
        verCaps.setContentAreaFilled(false);
        verCaps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verCaps.setDefaultCapable(false);
        verCaps.setOpaque(true);
        verCaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verCapsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verCapsMouseExited(evt);
            }
        });
        verCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCapsActionPerformed(evt);
            }
        });
        panelMostrarContenido.add(verCaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 120, 30));

        volver.setBackground(new java.awt.Color(255, 0, 0));
        volver.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setDefaultCapable(false);
        volver.setOpaque(true);
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        panelMostrarContenido.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 150, 40));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("JAVAFLIX");
        panelMostrarContenido.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, 50));

        panelCrearModificarSerie.setBackground(new java.awt.Color(0, 0, 0));
        panelCrearModificarSerie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearModificarContenido.setBackground(new java.awt.Color(255, 0, 0));
        crearModificarContenido.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        crearModificarContenido.setForeground(new java.awt.Color(255, 255, 255));
        crearModificarContenido.setText("Crear Serie");
        crearModificarContenido.setBorderPainted(false);
        crearModificarContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearModificarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearModificarContenidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearModificarContenidoMouseExited(evt);
            }
        });
        crearModificarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearModificarContenidoActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(crearModificarContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 440, 100));

        borrarCapitulo.setBackground(new java.awt.Color(255, 0, 0));
        borrarCapitulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        borrarCapitulo.setForeground(new java.awt.Color(255, 255, 255));
        borrarCapitulo.setText("Borrar Capítulo");
        borrarCapitulo.setBorderPainted(false);
        borrarCapitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarCapitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarCapituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarCapituloMouseExited(evt);
            }
        });
        borrarCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCapituloActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(borrarCapitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 190, 50));

        addCapitulo.setBackground(new java.awt.Color(255, 0, 0));
        addCapitulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addCapitulo.setForeground(new java.awt.Color(255, 255, 255));
        addCapitulo.setText("Añadir Capítulo");
        addCapitulo.setBorderPainted(false);
        addCapitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCapitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCapituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCapituloMouseExited(evt);
            }
        });
        addCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCapituloActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(addCapitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 190, 50));

        listaCapitulos.setBackground(new java.awt.Color(255, 255, 255));
        listaCapitulos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        listaCapitulos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listaCapitulos.setForeground(new java.awt.Color(0, 0, 0));
        listaCapitulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaCapitulos);

        panelCrearModificarSerie.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 230, 50));

        listaTemporadas.setBackground(new java.awt.Color(255, 255, 255));
        listaTemporadas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        listaTemporadas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listaTemporadas.setForeground(new java.awt.Color(0, 0, 0));
        listaTemporadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaTemporadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaTemporadasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaTemporadas);

        panelCrearModificarSerie.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 230, 50));

        borrarTemporada.setBackground(new java.awt.Color(255, 0, 0));
        borrarTemporada.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        borrarTemporada.setForeground(new java.awt.Color(255, 255, 255));
        borrarTemporada.setText("Borrar Temporada");
        borrarTemporada.setBorderPainted(false);
        borrarTemporada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarTemporada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarTemporadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarTemporadaMouseExited(evt);
            }
        });
        borrarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTemporadaActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(borrarTemporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 190, 50));

        addTemporada.setBackground(new java.awt.Color(255, 0, 0));
        addTemporada.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addTemporada.setForeground(new java.awt.Color(255, 255, 255));
        addTemporada.setText("Añadir Temporada");
        addTemporada.setBorderPainted(false);
        addTemporada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTemporada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addTemporadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTemporadaMouseExited(evt);
            }
        });
        addTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTemporadaActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(addTemporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 190, 50));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Temporadas:");
        panelCrearModificarSerie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 30));

        imagenPortada.setEditable(false);
        imagenPortada.setBackground(new java.awt.Color(255, 255, 255));
        imagenPortada.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        imagenPortada.setForeground(new java.awt.Color(0, 0, 0));
        panelCrearModificarSerie.add(imagenPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 200, 40));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Imagen Portada:");
        panelCrearModificarSerie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, 30));

        addImagen.setBackground(new java.awt.Color(255, 0, 0));
        addImagen.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addImagen.setForeground(new java.awt.Color(255, 255, 255));
        addImagen.setText("...");
        addImagen.setBorderPainted(false);
        addImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addImagenMouseExited(evt);
            }
        });
        addImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImagenActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(addImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 40, 40));

        actores.setBackground(new java.awt.Color(255, 255, 255));
        actores.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        actores.setForeground(new java.awt.Color(0, 0, 0));
        panelCrearModificarSerie.add(actores, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 410, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Actores (separados por comas seguidas de espacio):");
        panelCrearModificarSerie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 490, 30));

        anno.setBackground(new java.awt.Color(255, 255, 255));
        anno.setForeground(new java.awt.Color(0, 0, 0));
        anno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));
        panelCrearModificarSerie.add(anno, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, 70, 40));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año:");
        panelCrearModificarSerie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Género:");
        panelCrearModificarSerie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, 20));

        genero.setBackground(new java.awt.Color(255, 255, 255));
        genero.setForeground(new java.awt.Color(0, 0, 0));
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Catástrofe", "Ciencia Ficción", "Comedia", "Drama", "Fantasía", "Musicales", "Suspense", "Terror" }));
        panelCrearModificarSerie.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 160, 40));

        sinopsis.setBackground(new java.awt.Color(255, 255, 255));
        sinopsis.setColumns(20);
        sinopsis.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sinopsis.setForeground(new java.awt.Color(0, 0, 0));
        sinopsis.setLineWrap(true);
        sinopsis.setRows(5);
        sinopsis.setWrapStyleWord(true);
        sinopsis.setAlignmentX(3.0F);
        sinopsis.setAlignmentY(3.0F);
        jScrollPane1.setViewportView(sinopsis);

        panelCrearModificarSerie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 440, 180));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sinopsis:");
        panelCrearModificarSerie.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Título:");
        panelCrearModificarSerie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setEnabled(false);
        panelCrearModificarSerie.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 370, 40));

        tituloPantalla.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        tituloPantalla.setForeground(new java.awt.Color(255, 255, 255));
        tituloPantalla.setText("CREAR SERIE");
        panelCrearModificarSerie.add(tituloPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 547, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JAVAFLIX");
        panelCrearModificarSerie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 190, 50));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Capítulos:");
        panelCrearModificarSerie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 90, 30));

        previsualizar.setBackground(new java.awt.Color(255, 0, 0));
        previsualizar.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        previsualizar.setForeground(new java.awt.Color(255, 255, 255));
        previsualizar.setText("Previsualizar Serie");
        previsualizar.setBorderPainted(false);
        previsualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previsualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previsualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previsualizarMouseExited(evt);
            }
        });
        previsualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previsualizarActionPerformed(evt);
            }
        });
        panelCrearModificarSerie.add(previsualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 440, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(panelMostrarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelCrearModificarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panelMostrarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelCrearModificarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void crearModificarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearModificarContenidoActionPerformed
        if (!imagenPortada.getText().equals("") && !titulo.getText().equals("") && !sinopsis.getText().equals("") && !actores.getText().equals("")) {
            
            // Busca el archivo seleccionado
            String ruta = imagenPortada.getText();
            String[] carpetasRuta;
            if (ruta.contains("\\"))
                carpetasRuta = ruta.split("\\\\");
            else carpetasRuta = ruta.split("/");
            
            // Lo copia a la carpeta del programa
            archivo.moverImagen(imagenPortada.getText(), "img/imgcontenidos/" + carpetasRuta[carpetasRuta.length - 1]);
            
            if (crear) {
                Serie contenidoAdd = new Serie(capitulosTemporada, titulo.getText(), sinopsis.getText(), 
                        (String) genero.getSelectedItem(), 
                        (String) anno.getSelectedItem(), actores.getText().split(", "), "img/imgcontenidos/" + carpetasRuta[carpetasRuta.length - 1]);

                ((Administrador) usuario).crearContenido(contenidoAdd, contenidos);
                
            } else {

                ((Administrador) usuario).modificarContenido((Serie) contenidoSeleccionado, capitulosTemporada,
                        titulo.getText(), sinopsis.getText(), (String) genero.getSelectedItem(), (String) anno.getSelectedItem(),
                        actores.getText().split(", "), "img/imgcontenidos/" + carpetasRuta[carpetasRuta.length - 1]);

            }
            
            archivo.guardarArchivo("contenidos.dat", contenidos);
            this.dispose();

        } else JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_crearModificarContenidoActionPerformed

    
    // Si cierra la ventana se abre admin. de contenidos
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        AdministracionContenidos pantallaAdmin = new AdministracionContenidos();
        pantallaAdmin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    
    
    // Borra el capítulo seleccionado en el JList
    private void borrarCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCapituloActionPerformed

        if (!listaCapitulos.isSelectionEmpty()) {
           int indice = listaCapitulos.getSelectedIndex();
           int indiceTemporada = listaTemporadas.getSelectedIndex();
           capitulosTemporada.get(indiceTemporada).remove(indice);
           actualizarTemporadas();
           listaTemporadas.setSelectedIndex(indiceTemporada);
            
        } else JOptionPane.showMessageDialog(this, "No existen capitulos para borrar", "ERROR", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_borrarCapituloActionPerformed

    // Añade capítulo a la temporada seleccionada
    private void addCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCapituloActionPerformed

        try {

            String nombre = JOptionPane.showInputDialog(this, "Introduce el nombre del nuevo capítulo");
            if (!nombre.equals("")) {
                int duracion = Integer.parseInt(JOptionPane.showInputDialog(this, "Introduce la duración del nuevo capítulo"));
                capitulosTemporada.get(listaTemporadas.getSelectedIndex()).add(new Capitulo(nombre, duracion));
                actualizarCapitulos(listaTemporadas.getSelectedIndex());
            } else throw new NumberFormatException();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos mal introducidos. Capítulo no creado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addCapituloActionPerformed

    
    // Borra la temporada seleccionada y sus capítulos
    private void borrarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTemporadaActionPerformed

        if (!listaTemporadas.isSelectionEmpty()) {
            int temporadaBorrar = listaTemporadas.getSelectedIndex();
            int eleccion = JOptionPane.showOptionDialog(this, "¿Está seguro de que desea borrar la temporada " + (temporadaBorrar + 1) + "?"
                + " Ten en cuenta que se borrarán sus capítulos y la temporada " + (temporadaBorrar + 2) + " pasará a ser la " + (temporadaBorrar + 1)
                + " etc.",
                "Borrar Temporada", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
            if (eleccion == 0) {
                capitulosTemporada.remove(temporadaBorrar);
                actualizarTemporadas();
                listaTemporadas.setSelectedIndex(0);

            }
        } else JOptionPane.showMessageDialog(this, "Ninguna Temporada Seleccionada", "ERROR", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_borrarTemporadaActionPerformed

    // Añade una nueva temporada a la serie
    private void addTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTemporadaActionPerformed

        capitulosTemporada.add(new ArrayList<>());
        actualizarTemporadas();
        listaTemporadas.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Temporada Creada", "", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_addTemporadaActionPerformed

    // Actualiza los capítulos al cambiar la temporada
    private void listaTemporadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaTemporadasValueChanged
        if (!listaTemporadas.isSelectionEmpty())
            actualizarCapitulos(listaTemporadas.getSelectedIndex());
    }//GEN-LAST:event_listaTemporadasValueChanged
    
    // Abre JFileChooser y añade imagen
    private void addImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImagenActionPerformed
        String ruta = "";
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "jpg", "png", "gif", "svg");
        JFileChooser seleccionarImagen = new JFileChooser();
        seleccionarImagen.setFileFilter(filtro);
        seleccionarImagen.setMultiSelectionEnabled(false);

        if (seleccionarImagen.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta += seleccionarImagen.getSelectedFile().toString();
        }
        imagenPortada.setText(ruta);

    }//GEN-LAST:event_addImagenActionPerformed

    
    // Cambiar color del botón al entrar el ratón
    private void addImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addImagenMouseEntered
        addImagen.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_addImagenMouseEntered

    private void addImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addImagenMouseExited
        addImagen.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_addImagenMouseExited

    private void addTemporadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTemporadaMouseEntered
        addTemporada.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_addTemporadaMouseEntered

    private void addTemporadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTemporadaMouseExited
        addTemporada.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_addTemporadaMouseExited

    private void borrarTemporadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTemporadaMouseEntered
        borrarTemporada.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_borrarTemporadaMouseEntered

    private void borrarTemporadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTemporadaMouseExited
        borrarTemporada.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_borrarTemporadaMouseExited

    private void addCapituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCapituloMouseEntered
        addCapitulo.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_addCapituloMouseEntered

    private void addCapituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCapituloMouseExited
        addCapitulo.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_addCapituloMouseExited

    private void borrarCapituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarCapituloMouseEntered
        borrarCapitulo.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_borrarCapituloMouseEntered

    private void borrarCapituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarCapituloMouseExited
        borrarCapitulo.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_borrarCapituloMouseExited

    private void crearModificarContenidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearModificarContenidoMouseEntered
        crearModificarContenido.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_crearModificarContenidoMouseEntered

    private void crearModificarContenidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearModificarContenidoMouseExited
        crearModificarContenido.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_crearModificarContenidoMouseExited

    private void previsualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previsualizarMouseEntered
        previsualizar.setBackground(new java.awt.Color(94, 10, 10));
    }//GEN-LAST:event_previsualizarMouseEntered

    private void previsualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previsualizarMouseExited
        previsualizar.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_previsualizarMouseExited

    // Previsualiza la serie
    private void previsualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previsualizarActionPerformed
        Image portada = new ImageIcon(imagenPortada.getText()).getImage();
        imagen.setIcon(new ImageIcon(portada.getScaledInstance(290, 180, 100)));
        panelMostrarContenido.setVisible(true);
        panelCrearModificarSerie.setVisible(false);
        tituloMostrar.setText("<html>" + titulo.getText() + "</html>");
        sinopsisMostrar.setText(sinopsis.getText());
        actoresMostrar.setText("<html>" + actores.getText() + "</html>");
        genAnnoVal.setText(genero.getSelectedItem() + "   |   " + anno.getSelectedItem() + "   |   Valoración: 0");
        for (int i = 0 ; i < capitulosTemporada.size() ; i++) {
            temporadas.addItem("Temporada " + (i + 1));
        }
        try {
            temporadas.setSelectedIndex(0);
        } catch (IllegalArgumentException iae) {}
    }//GEN-LAST:event_previsualizarActionPerformed

    private void verCapsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCapsMouseEntered
        verCaps.setBackground(new java.awt.Color(94,10,10));
    }//GEN-LAST:event_verCapsMouseEntered

    private void verCapsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCapsMouseExited
        verCaps.setBackground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_verCapsMouseExited

    
    //  Muestra Capítulos de Temporada seleccionada
    private void verCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCapsActionPerformed
        int temporada = temporadas.getSelectedIndex();
        String capitulos = "";
        for (Capitulo capitulo : capitulosTemporada.get(temporada)) {
            capitulos += "Nombre: " + capitulo.getNombre() + "   |   Duración: " + String.valueOf(capitulo.getDuracion()) + "\n";
        }
        JOptionPane.showMessageDialog(this, capitulos, "Temporada " + (temporada + 1), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_verCapsActionPerformed

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new java.awt.Color(94,10,10));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_volverMouseExited

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // Vuelve a panelPresentación guardando los datos
        panelCrearModificarSerie.setVisible(true);
        panelMostrarContenido.setVisible(false);
        temporadas.removeAllItems();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearModificarSerie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actores;
    private javax.swing.JLabel actoresMostrar;
    private javax.swing.JButton addCapitulo;
    private javax.swing.JButton addImagen;
    private javax.swing.JButton addTemporada;
    private javax.swing.JComboBox<String> anno;
    private javax.swing.JButton borrarCapitulo;
    private javax.swing.JButton borrarTemporada;
    private javax.swing.JComboBox<String> calificacion;
    private javax.swing.JButton crearModificarContenido;
    private javax.swing.JButton favoritos;
    private javax.swing.JLabel genAnnoVal;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel imagen;
    private javax.swing.JTextField imagenPortada;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaCapitulos;
    private javax.swing.JList<String> listaTemporadas;
    private javax.swing.JPanel panelCrearModificarSerie;
    private javax.swing.JPanel panelMostrarContenido;
    private javax.swing.JButton previsualizar;
    private javax.swing.JTextArea sinopsis;
    private javax.swing.JTextArea sinopsisMostrar;
    private javax.swing.JComboBox<String> temporadas;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloMostrar;
    private javax.swing.JLabel tituloPantalla;
    private javax.swing.JButton verCaps;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    // Mis métodos
    
    /**
     * Carga las temporadas en su JList
     */
    private void actualizarTemporadas() {
        String[] temporadasImprimir = new String[capitulosTemporada.size()];
        for (int i = 0 ; i < temporadasImprimir.length ; i++) {
            temporadasImprimir[i] = "Temporada " + (i+1);
        }
        listaTemporadas.setListData(temporadasImprimir);
    }
    
    /**
     * Carga los capítulos de la temporada en el JList
     * 
     * @param temporadaSeleccionada temporada de la que hay que cargar los capitulos
     */
    private void actualizarCapitulos(int temporadaSeleccionada) {
        String[] capitulosImprimir = new String[capitulosTemporada.get(temporadaSeleccionada).size()];
        for (int i = 0 ; i < capitulosImprimir.length ; i++) {
            capitulosImprimir[i] = capitulosTemporada.get(listaTemporadas.getSelectedIndex()).get(i).getNombre();
        }
        listaCapitulos.setListData(capitulosImprimir);
    }

}
